import {
  DigitalAsset,
  Trade,
  SubledgerEntry,
  TaxLot,
  DisposedLot,
  JournalEntry,
  Counterparty,
  Settlement,
  TreasuryTransaction,
  ReconAssetBalance,
  ReconBreak,
  ReconHistoryPoint,
  Guardrail,
  SODControl,
  AuditLogEntry,
} from './types';

// Digital Assets
export const digitalAssets: DigitalAsset[] = [
  {
    id: 'BTC',
    symbol: 'BTC',
    name: 'Bitcoin',
    quantity: 1240.5,
    price: 67420,
    value: 83628174,
    unrealizedPnL: 28874589,
    allocation: 33.8,
  },
  {
    id: 'ETH',
    symbol: 'ETH',
    name: 'Ethereum',
    quantity: 28400,
    price: 3840,
    value: 109056000,
    unrealizedPnL: 42580000,
    allocation: 44.1,
  },
  {
    id: 'SOL',
    symbol: 'SOL',
    name: 'Solana',
    quantity: 185000,
    price: 185,
    value: 34225000,
    unrealizedPnL: 12450000,
    allocation: 13.8,
  },
  {
    id: 'USDC',
    symbol: 'USDC',
    name: 'USD Coin',
    quantity: 18200000,
    price: 1,
    value: 18200000,
    unrealizedPnL: 0,
    allocation: 7.4,
  },
  {
    id: 'USDT',
    symbol: 'USDT',
    name: 'Tether',
    quantity: 2290000,
    price: 1,
    value: 2290000,
    unrealizedPnL: 0,
    allocation: 0.9,
  },
];

// Trades
export const trades: Trade[] = [
  {
    id: 'TRD001',
    timestamp: new Date(Date.now() - 5 * 60000),
    exchange: 'Coinbase Pro',
    asset: 'BTC',
    side: 'Buy',
    quantity: 0.5,
    price: 67420,
    total: 33710,
    status: 'Settled',
    fee: 101.13,
  },
  {
    id: 'TRD002',
    timestamp: new Date(Date.now() - 15 * 60000),
    exchange: 'Kraken',
    asset: 'ETH',
    side: 'Sell',
    quantity: 5,
    price: 3840,
    total: 19200,
    status: 'Settled',
    fee: 57.6,
  },
  {
    id: 'TRD003',
    timestamp: new Date(Date.now() - 25 * 60000),
    exchange: 'Coinbase Pro',
    asset: 'SOL',
    side: 'Buy',
    quantity: 100,
    price: 185,
    total: 18500,
    status: 'Settled',
    fee: 55.5,
  },
  {
    id: 'TRD004',
    timestamp: new Date(Date.now() - 45 * 60000),
    exchange: 'Kraken',
    asset: 'BTC',
    side: 'Sell',
    quantity: 0.25,
    price: 67380,
    total: 16845,
    status: 'Confirmed',
    fee: 50.535,
  },
  {
    id: 'TRD005',
    timestamp: new Date(Date.now() - 2 * 3600000),
    exchange: 'Binance',
    asset: 'ETH',
    side: 'Buy',
    quantity: 10,
    price: 3835,
    total: 38350,
    status: 'Settled',
    fee: 115.05,
  },
  {
    id: 'TRD006',
    timestamp: new Date(Date.now() - 3 * 3600000),
    exchange: 'Gemini',
    asset: 'USDC',
    side: 'Buy',
    quantity: 50000,
    price: 1,
    total: 50000,
    status: 'Settled',
    fee: 100,
  },
  {
    id: 'TRD007',
    timestamp: new Date(Date.now() - 4 * 3600000),
    exchange: 'Coinbase Pro',
    asset: 'SOL',
    side: 'Sell',
    quantity: 500,
    price: 184.8,
    total: 92400,
    status: 'Settled',
    fee: 277.2,
  },
  {
    id: 'TRD008',
    timestamp: new Date(Date.now() - 6 * 3600000),
    exchange: 'Kraken',
    asset: 'BTC',
    side: 'Buy',
    quantity: 1,
    price: 67500,
    total: 67500,
    status: 'Pending',
    fee: 202.5,
  },
  {
    id: 'TRD009',
    timestamp: new Date(Date.now() - 8 * 3600000),
    exchange: 'Binance',
    asset: 'ETH',
    side: 'Sell',
    quantity: 15,
    price: 3842,
    total: 57630,
    status: 'Settled',
    fee: 172.89,
  },
  {
    id: 'TRD010',
    timestamp: new Date(Date.now() - 12 * 3600000),
    exchange: 'Gemini',
    asset: 'USDT',
    side: 'Buy',
    quantity: 100000,
    price: 1,
    total: 100000,
    status: 'Settled',
    fee: 200,
  },
];

// Subledger Entries
export const subledgerEntries: SubledgerEntry[] = [
  {
    id: 'SL001',
    date: new Date('2024-11-15'),
    asset: 'BTC',
    type: 'Purchase',
    quantity: 5,
    costBasis: 330000,
    marketValue: 337100,
    unrealizedPnL: 7100,
    glAccount: '1010-Digital Assets',
    status: 'Posted',
    counterparty: 'Coinbase Prime',
  },
  {
    id: 'SL002',
    date: new Date('2024-11-18'),
    asset: 'ETH',
    type: 'Purchase',
    quantity: 100,
    costBasis: 380000,
    marketValue: 384000,
    unrealizedPnL: 4000,
    glAccount: '1010-Digital Assets',
    status: 'Posted',
    counterparty: 'Kraken',
  },
  {
    id: 'SL003',
    date: new Date('2024-11-20'),
    asset: 'SOL',
    type: 'Purchase',
    quantity: 5000,
    costBasis: 925000,
    marketValue: 925000,
    unrealizedPnL: 0,
    glAccount: '1010-Digital Assets',
    status: 'Posted',
    counterparty: 'Binance',
  },
  {
    id: 'SL004',
    date: new Date('2024-11-22'),
    asset: 'BTC',
    type: 'Sale',
    quantity: 2,
    costBasis: 134400,
    marketValue: 134840,
    unrealizedPnL: 440,
    glAccount: '6010-Realized Gains',
    status: 'Posted',
    counterparty: 'Coinbase Prime',
  },
  {
    id: 'SL005',
    date: new Date('2024-11-25'),
    asset: 'ETH',
    type: 'Transfer',
    quantity: 10,
    costBasis: 38000,
    marketValue: 38400,
    unrealizedPnL: 400,
    glAccount: '1010-Digital Assets',
    status: 'Unposted',
    counterparty: 'Fireblocks',
  },
  {
    id: 'SL006',
    date: new Date('2024-11-26'),
    asset: 'USDC',
    type: 'Purchase',
    quantity: 1000000,
    costBasis: 1000000,
    marketValue: 1000000,
    unrealizedPnL: 0,
    glAccount: '1010-Digital Assets',
    status: 'Posted',
    counterparty: 'Gemini',
  },
  {
    id: 'SL007',
    date: new Date('2024-11-27'),
    asset: 'SOL',
    type: 'Staking',
    quantity: 1000,
    costBasis: 185000,
    marketValue: 185000,
    unrealizedPnL: 0,
    glAccount: '1011-Staked Assets',
    status: 'Posted',
  },
  {
    id: 'SL008',
    date: new Date('2024-11-28'),
    asset: 'ETH',
    type: 'Reward',
    quantity: 0.5,
    costBasis: 1920,
    marketValue: 1920,
    unrealizedPnL: 0,
    glAccount: '4010-Staking Rewards',
    status: 'Unposted',
  },
  {
    id: 'SL009',
    date: new Date('2024-11-29'),
    asset: 'BTC',
    type: 'Fee',
    quantity: 0.001,
    costBasis: 67.42,
    marketValue: 67.42,
    unrealizedPnL: 0,
    glAccount: '6050-Network Fees',
    status: 'Posted',
  },
  {
    id: 'SL010',
    date: new Date('2024-12-01'),
    asset: 'USDT',
    type: 'Purchase',
    quantity: 500000,
    costBasis: 500000,
    marketValue: 500000,
    unrealizedPnL: 0,
    glAccount: '1010-Digital Assets',
    status: 'Posted',
    counterparty: 'Kraken',
  },
  {
    id: 'SL011',
    date: new Date('2024-12-02'),
    asset: 'BTC',
    type: 'Transfer',
    quantity: 1,
    costBasis: 67420,
    marketValue: 67420,
    unrealizedPnL: 0,
    glAccount: '1010-Digital Assets',
    status: 'Unposted',
    counterparty: 'BitGo',
  },
  {
    id: 'SL012',
    date: new Date('2024-12-03'),
    asset: 'ETH',
    type: 'Purchase',
    quantity: 50,
    costBasis: 192000,
    marketValue: 192000,
    unrealizedPnL: 0,
    glAccount: '1010-Digital Assets',
    status: 'Posted',
    counterparty: 'Binance',
  },
];

// Tax Lots (Open)
export const taxLots: TaxLot[] = [
  {
    id: 'TL001',
    asset: 'BTC',
    acquiredDate: new Date('2023-01-15'),
    quantity: 100,
    costPerUnit: 45000,
    costBasis: 4500000,
    marketPerUnit: 67420,
    marketValue: 6742000,
    holdingPeriodDays: 450,
    isLongTerm: true,
  },
  {
    id: 'TL002',
    asset: 'BTC',
    acquiredDate: new Date('2024-08-10'),
    quantity: 200,
    costPerUnit: 60000,
    costBasis: 12000000,
    marketPerUnit: 67420,
    marketValue: 13484000,
    holdingPeriodDays: 116,
    isLongTerm: false,
  },
  {
    id: 'TL003',
    asset: 'ETH',
    acquiredDate: new Date('2023-03-20'),
    quantity: 5000,
    costPerUnit: 2000,
    costBasis: 10000000,
    marketPerUnit: 3840,
    marketValue: 19200000,
    holdingPeriodDays: 425,
    isLongTerm: true,
  },
  {
    id: 'TL004',
    asset: 'ETH',
    acquiredDate: new Date('2024-07-05'),
    quantity: 8000,
    costPerUnit: 3500,
    costBasis: 28000000,
    marketPerUnit: 3840,
    marketValue: 30720000,
    holdingPeriodDays: 151,
    isLongTerm: false,
  },
  {
    id: 'TL005',
    asset: 'SOL',
    acquiredDate: new Date('2023-10-01'),
    quantity: 50000,
    costPerUnit: 150,
    costBasis: 7500000,
    marketPerUnit: 185,
    marketValue: 9250000,
    holdingPeriodDays: 430,
    isLongTerm: true,
  },
  {
    id: 'TL006',
    asset: 'SOL',
    acquiredDate: new Date('2024-09-15'),
    quantity: 80000,
    costPerUnit: 175,
    costBasis: 14000000,
    marketPerUnit: 185,
    marketValue: 14800000,
    holdingPeriodDays: 110,
    isLongTerm: false,
  },
  {
    id: 'TL007',
    asset: 'USDC',
    acquiredDate: new Date('2024-06-01'),
    quantity: 18200000,
    costPerUnit: 1,
    costBasis: 18200000,
    marketPerUnit: 1,
    marketValue: 18200000,
    holdingPeriodDays: 220,
    isLongTerm: false,
  },
];

// Disposed Lots
export const disposedLots: DisposedLot[] = [
  {
    id: 'DL001',
    asset: 'BTC',
    disposedDate: new Date('2024-11-10'),
    quantity: 10,
    costBasis: 450000,
    proceeds: 689420,
    realizedGain: 239420,
    isLongTerm: true,
    method: 'FIFO',
  },
  {
    id: 'DL002',
    asset: 'ETH',
    disposedDate: new Date('2024-11-20'),
    quantity: 500,
    costBasis: 1200000,
    proceeds: 1920000,
    realizedGain: 720000,
    isLongTerm: true,
    method: 'FIFO',
  },
  {
    id: 'DL003',
    asset: 'BTC',
    disposedDate: new Date('2024-12-01'),
    quantity: 5,
    costBasis: 300000,
    proceeds: 340000,
    realizedGain: 40000,
    isLongTerm: false,
    method: 'HIFO',
  },
  {
    id: 'DL004',
    asset: 'SOL',
    disposedDate: new Date('2024-10-15'),
    quantity: 5000,
    costBasis: 825000,
    proceeds: 925000,
    realizedGain: 100000,
    isLongTerm: true,
    method: 'FIFO',
  },
  {
    id: 'DL005',
    asset: 'ETH',
    disposedDate: new Date('2024-11-05'),
    quantity: 100,
    costPerUnit: 2500,
    costBasis: 250000,
    proceeds: 384000,
    realizedGain: 134000,
    isLongTerm: false,
    method: 'LIFO',
  },
];

// Journal Entries
export const journalEntries: JournalEntry[] = [
  {
    id: 'JE001',
    date: new Date('2024-11-30'),
    reference: 'BTC Purchase 11-15',
    description: 'Purchase of 5 BTC @ $45,000',
    totalDebit: 225000,
    totalCredit: 225000,
    lineItems: [
      {
        lineId: '001',
        account: '1010',
        accountName: 'Digital Assets - Crypto',
        debit: 225000,
        credit: 0,
        description: 'BTC purchase',
      },
      {
        lineId: '002',
        account: '2050',
        accountName: 'Accounts Payable - Exchanges',
        debit: 0,
        credit: 225000,
        description: 'BTC purchase liability',
      },
    ],
    status: 'Pushed',
    erpFormat: 'NetSuite',
    pushedAt: new Date('2024-11-30'),
  },
  {
    id: 'JE002',
    date: new Date('2024-11-30'),
    reference: 'ETH Purchase 11-18',
    description: 'Purchase of 100 ETH @ $3,800',
    totalDebit: 380000,
    totalCredit: 380000,
    lineItems: [
      {
        lineId: '001',
        account: '1010',
        accountName: 'Digital Assets - Crypto',
        debit: 380000,
        credit: 0,
        description: 'ETH purchase',
      },
      {
        lineId: '002',
        account: '2050',
        accountName: 'Accounts Payable - Exchanges',
        debit: 0,
        credit: 380000,
        description: 'ETH purchase liability',
      },
    ],
    status: 'Pushed',
    erpFormat: 'SAP',
    pushedAt: new Date('2024-11-30'),
  },
  {
    id: 'JE003',
    date: new Date('2024-12-02'),
    reference: 'BTC Sale 11-22',
    description: 'Sale of 2 BTC @ $67,420',
    totalDebit: 134840,
    totalCredit: 134840,
    lineItems: [
      {
        lineId: '001',
        account: '1020',
        accountName: 'Cash - USD',
        debit: 134840,
        credit: 0,
        description: 'Proceeds from BTC sale',
      },
      {
        lineId: '002',
        account: '1010',
        accountName: 'Digital Assets - Crypto',
        debit: 0,
        credit: 134400,
        description: 'Cost basis of BTC sold',
      },
      {
        lineId: '003',
        account: '6010',
        accountName: 'Realized Gains',
        debit: 0,
        credit: 440,
        description: 'Gain on BTC sale',
      },
    ],
    status: 'Pushed',
    erpFormat: 'Oracle',
    pushedAt: new Date('2024-12-02'),
  },
  {
    id: 'JE004',
    date: new Date('2024-12-03'),
    reference: 'SOL Purchase 11-20',
    description: 'Purchase of 5,000 SOL @ $185',
    totalDebit: 925000,
    totalCredit: 925000,
    lineItems: [
      {
        lineId: '001',
        account: '1010',
        accountName: 'Digital Assets - Crypto',
        debit: 925000,
        credit: 0,
        description: 'SOL purchase',
      },
      {
        lineId: '002',
        account: '2050',
        accountName: 'Accounts Payable - Exchanges',
        debit: 0,
        credit: 925000,
        description: 'SOL purchase liability',
      },
    ],
    status: 'Ready to Push',
    erpFormat: 'NetSuite',
  },
  {
    id: 'JE005',
    date: new Date('2024-12-03'),
    reference: 'USDC Purchase 11-26',
    description: 'Purchase of 1,000,000 USDC @ $1.00',
    totalDebit: 1000000,
    totalCredit: 1000000,
    lineItems: [
      {
        lineId: '001',
        account: '1010',
        accountName: 'Digital Assets - Crypto',
        debit: 1000000,
        credit: 0,
        description: 'USDC purchase',
      },
      {
        lineId: '002',
        account: '2050',
        accountName: 'Accounts Payable - Exchanges',
        debit: 0,
        credit: 1000000,
        description: 'USDC purchase liability',
      },
    ],
    status: 'Ready to Push',
    erpFormat: 'SAP',
  },
  {
    id: 'JE006',
    date: new Date('2024-12-04'),
    reference: 'SOL Staking Reward 11-27',
    description: 'Staking reward received - 100 SOL',
    totalDebit: 18500,
    totalCredit: 18500,
    lineItems: [
      {
        lineId: '001',
        account: '1010',
        accountName: 'Digital Assets - Crypto',
        debit: 18500,
        credit: 0,
        description: 'Staking reward received',
      },
      {
        lineId: '002',
        account: '4010',
        accountName: 'Staking Rewards',
        debit: 0,
        credit: 18500,
        description: 'Staking reward income',
      },
    ],
    status: 'Draft',
  },
  {
    id: 'JE007',
    date: new Date('2024-12-04'),
    reference: 'USDT Purchase 12-01',
    description: 'Purchase of 500,000 USDT @ $1.00',
    totalDebit: 500000,
    totalCredit: 500000,
    lineItems: [
      {
        lineId: '001',
        account: '1010',
        accountName: 'Digital Assets - Crypto',
        debit: 500000,
        credit: 0,
        description: 'USDT purchase',
      },
      {
        lineId: '002',
        account: '2050',
        accountName: 'Accounts Payable - Exchanges',
        debit: 0,
        credit: 500000,
        description: 'USDT purchase liability',
      },
    ],
    status: 'Ready to Push',
    erpFormat: 'Workday',
  },
];

// Counterparties
export const counterparties: Counterparty[] = [
  {
    id: 'CP001',
    name: 'Coinbase Prime',
    type: 'Custodian',
    riskRating: 'Low',
    allocations: ['BTC', 'ETH', 'USDC'],
  },
  {
    id: 'CP002',
    name: 'Fireblocks',
    type: 'Custodian',
    riskRating: 'Low',
    allocations: ['BTC', 'ETH', 'SOL', 'USDT'],
  },
  {
    id: 'CP003',
    name: 'BitGo',
    type: 'Custodian',
    riskRating: 'Low',
    allocations: ['BTC', 'ETH'],
  },
  {
    id: 'CP004',
    name: 'Anchorage',
    type: 'Custodian',
    riskRating: 'Low',
    allocations: ['BTC', 'SOL'],
  },
];

// Settlements
export const settlements: Settlement[] = [
  {
    id: 'SET001',
    date: new Date('2024-12-01'),
    asset: 'BTC',
    quantity: 1,
    counterparty: 'Coinbase Prime',
    status: 'Settled',
    expectedDate: new Date('2024-12-01'),
  },
  {
    id: 'SET002',
    date: new Date('2024-12-02'),
    asset: 'ETH',
    quantity: 25,
    counterparty: 'Fireblocks',
    status: 'Settled',
    expectedDate: new Date('2024-12-02'),
  },
  {
    id: 'SET003',
    date: new Date('2024-12-04'),
    asset: 'SOL',
    quantity: 5000,
    counterparty: 'BitGo',
    status: 'In Transit',
    expectedDate: new Date('2024-12-05'),
  },
  {
    id: 'SET004',
    date: new Date('2024-12-04'),
    asset: 'USDC',
    quantity: 100000,
    counterparty: 'Anchorage',
    status: 'Pending',
    expectedDate: new Date('2024-12-06'),
  },
  {
    id: 'SET005',
    date: new Date('2024-12-03'),
    asset: 'BTC',
    quantity: 0.5,
    counterparty: 'Fireblocks',
    status: 'Settled',
    expectedDate: new Date('2024-12-03'),
  },
  {
    id: 'SET006',
    date: new Date('2024-12-04'),
    asset: 'USDT',
    quantity: 250000,
    counterparty: 'Coinbase Prime',
    status: 'Pending',
    expectedDate: new Date('2024-12-07'),
  },
  {
    id: 'SET007',
    date: new Date('2024-12-04'),
    asset: 'ETH',
    quantity: 10,
    counterparty: 'Anchorage',
    status: 'In Transit',
    expectedDate: new Date('2024-12-05'),
  },
];

// Treasury Transactions
export const treasuryTransactions: TreasuryTransaction[] = [
  {
    id: 'TTX001',
    date: new Date('2024-12-01'),
    type: 'Inbound',
    asset: 'BTC',
    quantity: 2,
    sourceCounterparty: 'Coinbase Prime',
    destinationCounterparty: 'Internal',
    status: 'Settled',
  },
  {
    id: 'TTX002',
    date: new Date('2024-12-01'),
    type: 'Outbound',
    asset: 'ETH',
    quantity: 50,
    sourceCounterparty: 'Internal',
    destinationCounterparty: 'Fireblocks',
    status: 'Settled',
  },
  {
    id: 'TTX003',
    date: new Date('2024-12-02'),
    type: 'Internal Transfer',
    asset: 'SOL',
    quantity: 10000,
    sourceCounterparty: 'Fireblocks',
    destinationCounterparty: 'BitGo',
    status: 'Settled',
  },
  {
    id: 'TTX004',
    date: new Date('2024-12-02'),
    type: 'Inbound',
    asset: 'USDC',
    quantity: 500000,
    sourceCounterparty: 'Coinbase Prime',
    destinationCounterparty: 'Internal',
    status: 'Settled',
  },
  {
    id: 'TTX005',
    date: new Date('2024-12-03'),
    type: 'Outbound',
    asset: 'BTC',
    quantity: 0.5,
    sourceCounterparty: 'Internal',
    destinationCounterparty: 'Anchorage',
    status: 'Pending',
  },
  {
    id: 'TTX006',
    date: new Date('2024-12-04'),
    type: 'Internal Transfer',
    asset: 'USDT',
    quantity: 1000000,
    sourceCounterparty: 'Coinbase Prime',
    destinationCounterparty: 'Fireblocks',
    status: 'Pending',
  },
];

// Reconciliation - Asset Balances
export const reconAssetBalances: ReconAssetBalance[] = [
  {
    asset: 'BTC',
    bookBalance: 1240.5,
    exchangeBalance: 1240.5,
    blockchainBalance: 1240.5,
    bookMatched: true,
    exchangeMatched: true,
    blockchainMatched: true,
  },
  {
    asset: 'ETH',
    bookBalance: 28400,
    exchangeBalance: 28395,
    blockchainBalance: 28400,
    bookMatched: true,
    exchangeMatched: false,
    blockchainMatched: true,
  },
  {
    asset: 'SOL',
    bookBalance: 185000,
    exchangeBalance: 185000,
    blockchainBalance: 184998,
    bookMatched: true,
    exchangeMatched: true,
    blockchainMatched: false,
  },
  {
    asset: 'USDC',
    bookBalance: 18200000,
    exchangeBalance: 18200000,
    blockchainBalance: 18200000,
    bookMatched: true,
    exchangeMatched: true,
    blockchainMatched: true,
  },
  {
    asset: 'USDT',
    bookBalance: 2290000,
    exchangeBalance: 2290000,
    blockchainBalance: 2289999.5,
    bookMatched: true,
    exchangeMatched: true,
    blockchainMatched: false,
  },
];

// Reconciliation - Breaks
export const reconBreaks: ReconBreak[] = [
  {
    id: 'BREAK001',
    date: new Date('2024-12-02'),
    asset: 'ETH',
    difference: 5,
    source: 'Book vs Exchange',
    status: 'Investigating',
    investigator: 'Alice Chen',
  },
  {
    id: 'BREAK002',
    date: new Date('2024-12-03'),
    asset: 'SOL',
    difference: 2,
    source: 'Book vs Blockchain',
    status: 'Open',
  },
  {
    id: 'BREAK003',
    date: new Date('2024-12-01'),
    asset: 'USDT',
    difference: 0.5,
    source: 'Book vs Blockchain',
    status: 'Resolved',
    investigator: 'Bob Smith',
  },
  {
    id: 'BREAK004',
    date: new Date('2024-12-04'),
    asset: 'ETH',
    difference: 2,
    source: 'Exchange vs Blockchain',
    status: 'Open',
  },
];

// Reconciliation - History
export const reconHistory: ReconHistoryPoint[] = [
  { date: new Date('2024-11-28'), percentageMatched: 95, brokenAssets: 2 },
  { date: new Date('2024-11-29'), percentageMatched: 96, brokenAssets: 1 },
  { date: new Date('2024-11-30'), percentageMatched: 98, brokenAssets: 1 },
  { date: new Date('2024-12-01'), percentageMatched: 97, brokenAssets: 2 },
  { date: new Date('2024-12-02'), percentageMatched: 96, brokenAssets: 3 },
  { date: new Date('2024-12-03'), percentageMatched: 95, brokenAssets: 3 },
  { date: new Date('2024-12-04'), percentageMatched: 92, brokenAssets: 4 },
];

// Guardrails
export const guardrails: Guardrail[] = [
  {
    id: 'GR001',
    name: 'Max Counterparty Concentration',
    description: 'Single counterparty exposure limit',
    threshold: 50000000,
    currentValue: 42500000,
    status: 'Pass',
    severity: 'Critical',
  },
  {
    id: 'GR002',
    name: 'Max Daily Trade Volume',
    description: 'Daily transaction volume limit',
    threshold: 100000000,
    currentValue: 78234500,
    status: 'Pass',
    severity: 'Critical',
  },
  {
    id: 'GR003',
    name: 'Unposted Subledger Entries',
    description: 'Max days of unposted entries',
    threshold: 7,
    currentValue: 3,
    status: 'Pass',
    severity: 'Warning',
  },
  {
    id: 'GR004',
    name: 'Recon Breaks Threshold',
    description: 'Max open reconciliation breaks',
    threshold: 5,
    currentValue: 4,
    status: 'Pass',
    severity: 'Warning',
  },
  {
    id: 'GR005',
    name: 'Tax Lot Ambiguity',
    description: 'Unspecified disposal method',
    threshold: 0,
    currentValue: 2,
    status: 'Warning',
    severity: 'Info',
  },
  {
    id: 'GR006',
    name: 'JE Queue Backlog',
    description: 'Pending journal entries in queue',
    threshold: 30,
    currentValue: 23,
    status: 'Pass',
    severity: 'Info',
  },
];

// SOD Controls
export const sodControls: SODControl[] = [
  {
    id: 'SOD001',
    controlName: 'Trade Authorization Segregation',
    authority: 'Treasurer',
    action: 'Trade Initiation',
    status: 'Compliant',
    lastTestDate: new Date('2024-12-01'),
  },
  {
    id: 'SOD002',
    controlName: 'Subledger Post Authority',
    authority: 'Controller',
    action: 'Subledger Post',
    status: 'Compliant',
    lastTestDate: new Date('2024-12-01'),
  },
  {
    id: 'SOD003',
    controlName: 'JE Approval Authority',
    authority: 'Finance Manager',
    action: 'JE Approval',
    status: 'Compliant',
    lastTestDate: new Date('2024-11-30'),
  },
  {
    id: 'SOD004',
    controlName: 'ERP Push Authorization',
    authority: 'CFO',
    action: 'Push to NetSuite/SAP',
    status: 'Compliant',
    lastTestDate: new Date('2024-11-28'),
  },
  {
    id: 'SOD005',
    controlName: 'User Access Review',
    authority: 'IT Security',
    action: 'Access Provisioning',
    status: 'Compliant',
    lastTestDate: new Date('2024-11-15'),
  },
  {
    id: 'SOD006',
    controlName: 'Change Management',
    authority: 'CRO',
    action: 'Configuration Changes',
    status: 'Compliant',
    lastTestDate: new Date('2024-11-20'),
  },
];

// Audit Log
export const auditLog: AuditLogEntry[] = [
  {
    id: 'AUD001',
    timestamp: new Date(Date.now() - 5 * 60000),
    user: 'alice.chen@company.com',
    module: 'Trade Connect',
    action: 'Execute Trade',
    details: 'BTC/USD buy order 0.5 BTC @ $67,420',
    ipAddress: '192.168.1.100',
    status: 'Success',
  },
  {
    id: 'AUD002',
    timestamp: new Date(Date.now() - 15 * 60000),
    user: 'bob.smith@company.com',
    module: 'Subledger',
    action: 'Post Entry',
    details: 'Posted BTC purchase entry SL001',
    ipAddress: '192.168.1.101',
    status: 'Success',
  },
  {
    id: 'AUD003',
    timestamp: new Date(Date.now() - 30 * 60000),
    user: 'carol.white@company.com',
    module: 'Gain/Loss',
    action: 'Change Method',
    details: 'Changed tax lot method from FIFO to HIFO',
    ipAddress: '192.168.1.102',
    status: 'Success',
  },
  {
    id: 'AUD004',
    timestamp: new Date(Date.now() - 1 * 3600000),
    user: 'alice.chen@company.com',
    module: 'Journal Entries',
    action: 'Push to ERP',
    details: 'Pushed 3 JEs to NetSuite (batch ID: NET-20241204-001)',
    ipAddress: '192.168.1.100',
    status: 'Success',
  },
  {
    id: 'AUD005',
    timestamp: new Date(Date.now() - 2 * 3600000),
    user: 'david.lee@company.com',
    module: 'Reconciliation',
    action: 'Investigate Break',
    details: 'Opened investigation for ETH/Book vs Exchange break',
    ipAddress: '192.168.1.103',
    status: 'Success',
  },
  {
    id: 'AUD006',
    timestamp: new Date(Date.now() - 4 * 3600000),
    user: 'eve.martinez@company.com',
    module: 'Treasury',
    action: 'Allocate Assets',
    details: 'Rebalanced BTC allocation from Coinbase to Fireblocks',
    ipAddress: '192.168.1.104',
    status: 'Success',
  },
  {
    id: 'AUD007',
    timestamp: new Date(Date.now() - 6 * 3600000),
    user: 'frank.wilson@company.com',
    module: 'Security',
    action: 'View Audit Log',
    details: 'Accessed audit log - 2024 Q4 review',
    ipAddress: '192.168.1.105',
    status: 'Success',
  },
  {
    id: 'AUD008',
    timestamp: new Date(Date.now() - 8 * 3600000),
    user: 'alice.chen@company.com',
    module: 'Trade Connect',
    action: 'View Position',
    details: 'Viewed BTC position and P&L',
    ipAddress: '192.168.1.100',
    status: 'Success',
  },
];

// ERP Format Templates
export const erpTemplates = {
  NetSuite: (je: JournalEntry): string => {
    return `<?xml version="1.0" encoding="UTF-8"?>
<journalEntry>
  <externalId>${je.id}</externalId>
  <memo>${je.description}</memo>
  <tranDate>${je.date.toISOString().split('T')[0]}</tranDate>
  <lineList>
${je.lineItems.map((item) => `    <line>
      <account>${item.account}</account>
      <debit>${item.debit}</debit>
      <credit>${item.credit}</credit>
      <memo>${item.description}</memo>
    </line>`).join('\n')}
  </lineList>
</journalEntry>`;
  },

  SAP: (je: JournalEntry): string => {
    return `IDOC
HDR IDOC_BEGIN
  DOCNUM=${je.id}
  DOCTYPE=ORDERS05
  MESTYP=ORDERS
  EDIDC_SEG
EDP IDOC_DATA
${je.lineItems.map((item, idx) => `  E1EDPA1_ITEM_${idx + 1}
    POSNR=${String(idx + 1).padStart(6, '0')}
    MATNR=${je.id}
    QUANTITY=1
    NETPR=${item.debit || item.credit}
    E1EDPZ1_ITEM_${idx + 1}
      TVEURO=${item.description}
`).join('\n')}
IDOC_END`;
  },

  Oracle: (je: JournalEntry): string => {
    return JSON.stringify(
      {
        journalHeader: {
          journalName: `JE-${je.id}`,
          journalType: 'Standard',
          periodName: je.date.toISOString().split('T')[0],
          description: je.description,
          balanceType: 'Actual',
          postingStatus: 'U',
          lines: je.lineItems.map((item) => ({
            lineNumber: je.lineItems.indexOf(item) + 1,
            accountCode: item.account,
            description: item.description,
            debitAmount: item.debit,
            creditAmount: item.credit,
          })),
        },
      },
      null,
      2
    );
  },

  Workday: (je: JournalEntry): string => {
    return je.lineItems
      .map(
        (item, idx) =>
          `"${je.id}","${idx + 1}","${je.date
            .toISOString()
            .split('T')[0]}","${item.account}","${item.accountName}","${item.debit}","${item.credit}","${item.description}"`
      )
      .join('\n');
  },
};
